services:

  db:
    image: postgres:16
    container_name: codebase-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codebase

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: codebase-backend

    ports:
      - "8080:8080"

    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/codebase
      SECRET_KEY: change-this-to-a-long-random-secret
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      FRONTEND_URL: http://localhost:5173
      GOOGLE_CLIENT_ID: 173092224038-9p980u25gj0ihdbe46m2gru3rrs7ojgo.apps.googleusercontent.com

    depends_on:
      - db

volumes:
  postgres_data:
